//
//  TaskQueue.swift
//  AsyncUtils
//
//  Created by Matteo Ludwig on 29.11.23.
//  Licensed under the MIT-License included in the project.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//

import Foundation

/// A task queue that can be used to run tasks concurrently with a maximum number of tasks running at the same time. Task are executed in the order they are added to the queue (FIFO).
/// To provide more flexibility, tasks can be provided with a number of slots that they require. By default, a task requires 1 slot. Tasks will only be started if there are enough slots available. The TaskQueue will never violate FIFO order, so be careful when using slots to ensure that a task requiring more than 1 slot does not unintentionally block other tasks from being started. If you add a task with equal to or more slots than the maximum number of concurrent slots, it will never be started until the maximum number of concurrent slots is increased, effectively blocking the queue from processing any further tasks until the task is started or cancelled.
/// An optional `taskProvider` closure can be supplied to generate work on demand. It is called whenever the queue is empty and at least one concurrent slot is available, allowing the queue to pull new tasks rather than requiring them to be pushed.
/// - Note: The TaskQueue is an actor, so it is thread-safe and can be used from multiple threads without any additional synchronization.
public actor TaskQueue {
    

    // QueueTicket is defined as a top-level type below TaskQueue.

    // MARK: Internals
    
    /// A struct used to keep track of running tasks. For performance reasons, the number of slots used is included.
    private struct RunningTask {
        /// The number of slots used by the task.
        let slots: Int
        /// The task that is currently running.
        let task: Task<Void, Never>
    }
    
    /// The queue that holds the tasks that are waiting to be executed. Used to maintain the order of the tasks.
    private var queue: TicketQueue = .init()

    /// A map that holds the task IDs of the tasks that are currently in the queue. Used to prevent duplicate tasks from being added to the queue.
    private var queueTasks: [Ticket: QueueTask] = [:]

    /// A map that holds the tasks that are currently running. Used to keep track of the running tasks.
    private var runningTasks: [Ticket: RunningTask] = .init()
    
    /// A map used by `waitForAll()` to keep track of semaphores that are used to wait for all tasks to finish. The key is a unique ticket that is used to identify the semaphore.
    private var waitForAllSemaphores: [Ticket: AsyncSemaphore] = [:]

    /// An optional closure that is called on-demand to supply work whenever the explicit queue is empty and at least one slot is free.
    /// The closure receives the current number of free slots and may return a task to enqueue, or `nil` if no work is available right now.
    /// Invocations are serialized - the closure is never called concurrently with itself. Once it returns, it will be called again
    /// as long as the queue remains empty and free slots are available.
    /// - Note: `waitForAll()` only waits for tasks that were already queued or running at the time of the call. Tasks generated by
    ///   the provider after `waitForAll()` begins are not included in that wait.
    public private(set) var taskProvider: ((_ freeSlots: Int) async -> QueueTask?)? {
        didSet { triggerProviderIfNeeded() }
    }

    /// Prevents concurrent invocations of `taskProvider`.
    private var isProviderActive: Bool = false

    /// The priority of the tasks that are executed.
    public private(set) var defaultTaskPriority: TaskPriority?
    
    // MARK: Counts

    /// The number of tasks that are currently queued but not running.
    /// - Important: In almost all cases, you should not to access this value, as doing so will only lead to race conditions.
    public var queuedCount: Int {
        self.queue.count
    }
    
    /// The number of tasks that are currently running.
    /// - Important: In almost all cases, you should not to access this value, as doing so will only lead to race conditions.
    public var runningCount: Int {
        self.runningTasks.count
    }
    
    /// The number of slots that are currently used by running tasks.
    /// - Note: Since tasks can require more than 1 slot, this number can be greater than the number of running tasks.
    /// Even if there are tasks queued, this number may be less than the maximum number of concurrent slots when a task that requires more than 1 is be next in line to be started.
    /// - Important: In almost all cases, you should not to access this value, as doing so will only lead to race conditions.
    public var currentUsedSlots: Int {
        self.runningTasks.values.map(\.slots).reduce(0, +)
    }
    
    /// The total number of tasks that are currently queued or running.
    /// - Important: In almost all cases, you should not to access this value, as doing so will only lead to race conditions.
    public var count: Int {
        self.queuedCount + self.runningCount
    }
    
    /// The number of tasks that are currently queued or running.
    public struct Counts: Equatable {
        /// The number of tasks that are currently queued but not running.
        public let queued: Int

        /// The number of tasks that are currently running.
        public let running: Int
        
        /// The total number of tasks that are currently queued or running.
        public var count: Int { queued + running }
        
        /// Initializes a new counts struct.
        /// - Parameters: queued: The number of tasks that are currently queued but not running.
        /// - Parameters: running: The number of tasks that are currently running.
        public init(queued: Int, running: Int) {
            self.queued = queued
            self.running = running
        }
    }
    
    /// The number of tasks that are currently queued or running.
    /// - Important: In almost all cases, you should not to access this value, as doing so will only lead to race conditions.
    public var counts: Counts {
        .init(queued: self.queuedCount, running: self.runningCount)
    }
    
    /// The maximum number of tasks that can run concurrently. If this number is lowered while tasks are running, currently running tasks are not canceled. If this number is increased, the queue will start new tasks immediately if there are tasks in the queue that can be started.
    /// - Precondition: The maximum number of concurrent slots must be greater than 0.
    public private(set) var maxConcurrentSlots: Int = 1 {
        didSet {
            self.startNextTasks()
        }
    }

    // MARK: Init
    
    /// Initializes a new task queue.
    /// - Parameters:
    ///   - maxConcurrentSlots: The maximum number of tasks that can run concurrently.
    ///   - defaultTaskPriority: The priority used for tasks that do not specify their own priority.
    ///   - taskProvider: An optional closure called on-demand to supply work when the queue is empty and slots are free.
    /// - Precondition: The maximum number of concurrent slots must be greater than 0.
    public init(maxConcurrentSlots: Int = 1, defaultTaskPriority: TaskPriority? = nil, taskProvider: ((_ freeSlots: Int) async -> QueueTask?)? = nil) {
        precondition(maxConcurrentSlots > 0, "Maximum number of concurrent slots must be greater than 0.")

        self.maxConcurrentSlots = maxConcurrentSlots
        self.defaultTaskPriority = defaultTaskPriority
        self.taskProvider = taskProvider
        // didSet does not fire during init, so trigger manually if a provider was supplied.
        // init is nonisolated, so the Task does not inherit the actor's executor.
        // Awaiting a synchronous actor-isolated method from outside the actor is valid Swift -
        // the await represents the actor hop, not any async work inside the method.
        if taskProvider != nil {
            Task { [self] in await self.triggerProviderIfNeeded() }
        }
    }

    // MARK: Setters

    /// Sets the default priority for tasks added to the queue. Tasks that specify their own priority will not be affected.
    /// - Parameter defaultTaskPriority: The default priority to set for tasks added to the queue. If nil, the system default priority will be used.
    public func setDefaultTaskPriority(_ defaultTaskPriority: TaskPriority?) {
        self.defaultTaskPriority = defaultTaskPriority
    }

    /// Sets the task provider for the queue. The provider is called whenever the queue is empty and at least one slot is free, allowing the queue to pull new tasks rather than requiring them to be pushed.
    /// - Parameter taskProvider: An optional closure called on-demand to supply work when the queue is empty and slots are free. The closure receives the current number of free slots and may return a task to enqueue, or `nil` if no work is available right now.
    public func setTaskProvider(_ taskProvider: ((_ freeSlots: Int) async -> QueueTask?)?) {
        self.taskProvider = taskProvider
    }
    
    /// Sets the maximum number of concurrent slots for the queue. If this number is lowered while tasks are running, currently running tasks are not canceled. If this number is increased, the queue will start new tasks immediately if there are tasks in the queue that can be started.
    /// - Parameter maxConcurrentSlots: The maximum number of concurrent slots to set for the queue. The maximum number of concurrent slots must be greater than 0.
    public func setMaxConcurrentSlots(_ maxConcurrentSlots: Int) {
        precondition(maxConcurrentSlots > 0, "Maximum number of concurrent slots must be greater than 0.")
        self.maxConcurrentSlots = maxConcurrentSlots
    }

    // MARK: Starting Tasks

    /// Starts the next task if the number of running tasks is less than the maximum number of concurrent tasks.
    /// - Returns: The next task that is started or nil if no task is started.
    @discardableResult
    private func startNextTask() -> Bool {
        // Retrieve next task from the queue if there is one
        guard let ticket = queue.first else { return false }
        guard let task = queueTasks[ticket] else {
            preconditionFailure("Task Ticket not found.")
        }
        
        // Check that enough slots are available to start the task
        guard currentUsedSlots + task.slots <= maxConcurrentSlots else { return false }
        
        let taskPriority = task.taskPriority ?? defaultTaskPriority
        runningTasks[ticket] = .init(slots: task.slots, task: Task(priority: taskPriority, operation: task.closure))
        queue.dequeue()
        return true
    }
    
    /// Starts as many tasks as possible from the queue, then triggers the provider if the queue is now empty and slots remain.
    private func startNextTasks() {
        while startNextTask() {}
        triggerProviderIfNeeded()
    }

    /// Schedules a single call to `taskProvider` if all conditions are met: the provider is set, not already active,
    /// the explicit queue is empty, and at least one slot is free.
    private func triggerProviderIfNeeded() {
        guard let taskProvider else { return }
        guard !isProviderActive else { return }
        guard queue.isEmpty else { return }
        let freeSlots = maxConcurrentSlots - currentUsedSlots
        guard freeSlots > 0 else { return }

        isProviderActive = true
        Task {
            let providerTask = await taskProvider(freeSlots)
            // Task inherits the actor's executor, so no await needed for the synchronous actor method.
            self.handleProviderResult(providerTask)
        }
    }

    /// Called when `taskProvider` returns. Resets the active flag, enqueues the returned task if any,
    /// then re-checks whether the provider should be called again for remaining free slots.
    private func handleProviderResult(_ providerTask: QueueTask?) {
        isProviderActive = false
        guard let providerTask else { return }
        // `add` wraps the closure and calls `startNextTasks` internally.
        // Reset isProviderActive *before* calling add so that the startNextTasks
        //->triggerProviderIfNeeded path inside add can schedule the next provider
        // call for any remaining free slots.
        add(providerTask)
    }

    // MARK: Tickets
    
    /// Returns the Tickets of all tasks that are currently queued or running.
    /// - Returns: The Tickets of all tasks that are currently queued or running.
    private func allTickets() -> [Ticket] {
        var tasksAhead = queue.map(\.self)
        tasksAhead.append(contentsOf: self.runningTasks.keys)
        return tasksAhead
    }
    
    /// Registers a new task with the given number of slots. This is used to create a ticket for a task that can be added to the queue later.
    /// - Parameters: slots: The number of slots that the task requires. 
    /// - Returns: A QueueTicket under which the task is registered. This ticket can be used to access the task later, e.g., to cancel it or to wait for it to finish.
    private func registerTask(slots: Int) -> QueueTicket {
        let ticket = Ticket()
        queueTasks[ticket] = .init(slots: slots) {
        }
        return QueueTicket(.init(ticket: ticket))
    }

    // MARK: Task Completion

    /// Called when a task is finished. This method removes the task from the running tasks and starts the next tasks in the queue.
    /// - Parameters: ticket: The ticket of the task that is finished.
    /// - Parameters: continuationResume: A closure that is called to resume the continuation that is waiting for the task to finish. If the continuation has not been resumed yet, this closure is called to allow for it to resume.
    /// - Important: You must call this task every time a task is finished, either successfully or due to cancellation. This method will also start the next tasks in the queue if there are any.
    /// - Note: This method also signals any semaphores that are waiting for all tasks to finish, to notify them that a task has finished.
    private func completedTask(_ ticket: Ticket, _ continuationResume: @escaping () -> Void = {}) {

        // Remove the task from the running tasks
        runningTasks.removeValue(forKey: ticket)

        if let task = queueTasks.removeValue(forKey: ticket), !task.continuationResumed {
            // Resume the continuation if it has not been resumed yet
            continuationResume()
        }

        // Start the next tasks in the queue
        startNextTasks()
        
        // If there are semaphores waiting for all tasks to finish, signal them to notify that a task has finished.
        Task {
            for semaphore in waitForAllSemaphores.values {
                await semaphore.signal()
            }
        }
    }

    // MARK: Task Cancellation
    
    /// Cancels the task identified by the given ticket if it is not queued. Will cause inconsistent state if the task is still queued, so this method should only be used for tasks that are known to have already been started.
    /// - Parameter ticket: The ticket of the task to cancel.
    /// - Note: Cancellation is cooperative - a running task must check for cancellation itself (e.g. via `Task.checkCancellation()`) to stop early.
    private func cancelDequeuedTask(_ ticket: Ticket) {
        runningTasks[ticket]?.task.cancel()
        
        // Cancel the task and remove it from the tasks map
        queueTasks[ticket]?.cancel()

        if queueTasks[ticket]?.continuationResumed == true {
            // If the continuation has been resumed, we no longer need to keep the task in the tasks map
            queueTasks.removeValue(forKey: ticket)
        }
    }
    
    /// Cancels the task identified by the given QueueTicket.
    /// If the task is still queued, it is removed before it starts. If it is already running, the underlying `Task` is cancelled.
    /// The queue is then advanced, which may start other queued tasks or trigger `taskProvider` if capacity becomes available.
    /// - Parameter ticket: The ticket returned by `add` when the task was enqueued.
    /// - Parameter startNext: Whether to start the next tasks in the queue after cancellation. This should usually be true to ensure that the queue continues to process tasks, but can be set to false if you want to cancel multiple tasks in a row without starting any of them until all cancellations are done.
    /// - Note: Even if startNext is set to false, the cancellation of a running task will still invoke `completedTask`, which may invoke the start of queued tasks or trigger the provider. However, this is done asynchronously, so setting startNext to false can still be used to ensure that the queue does not synchronously start new tasks before multiple cancellations are processed. If you want to synchronously cancel multiple tasks without starting any of them, you can set startNext to false for all cancellations, and then call `startNextTasks()` manually after all cancellations are done.
    /// - Note: Cancellation is cooperative - a running task must check for cancellation itself (e.g. via `Task.checkCancellation()`) to stop early.
    private func cancel(_ queueTicket: QueueTicket, startNext: Bool) {

        // Remove the task from the queue or running tasks
        if queue.isEnqueued(queueTicket.node) {
            queue.remove(queueTicket.node)
        }
        
        cancelDequeuedTask(queueTicket.ticket)
        queueTasks.removeValue(forKey: queueTicket.ticket)
        if startNext {
            startNextTasks()
        }
    }
    
    /// Cancels the task identified by the given QueueTicket.
    /// If the task is still queued, it is removed before it starts. If it is already running, the underlying `Task` is cancelled.
    /// - Parameter ticket: The ticket returned by `add` when the task was enqueued.
    /// - Note: Cancellation is cooperative - a running task must check for cancellation itself (e.g. via `Task.checkCancellation()`) to stop early.
    public func cancel(_ queueTicket: QueueTicket) {
        cancel(queueTicket, startNext: true)
    }

    // MARK: Adding Tasks

        /// Adds a task to the queue. 
    /// - Parameters: task: The task that is added to the queue.
    /// - Parameters: queueTicket: The QueueTicket under which the task is registered. This ticket can be used to access the task later, e.g., to cancel it or to wait for it to finish.
    /// - Note: If a task with the same ticket is already in the queue, it is replaced by the new task.
    private func add(_ task: QueueTask, with queueTicket: QueueTicket) {
        queueTasks[queueTicket.ticket] = task
        queue.enqueue(node: queueTicket.node)
        startNextTasks()
    }
    
    /// Adds a task to the queue. 
    /// - Parameters: task: The task that is added to the queue.
    /// - Parameters: ticket: The ticket under which the task is registered. This ticket can be used to access the task later, e.g., to cancel it or to wait for it to finish.
    /// - Note: If a task with the same ticket is already in the queue, it is replaced by the new task.
    private func add(_ task: QueueTask, with ticket: Ticket) -> QueueTicket {
        queueTasks[ticket] = task
        let node = queue.enqueue(ticket)
        startNextTasks()
        return QueueTicket(node)
    }
    
    
    /// Adds a task to the queue.
    /// - Parameter QueueTask: The task to enqueue.
    /// - Returns: A `Ticket` that can be passed to `cancel(_:)` to cancel this specific task.
    @discardableResult
    public func add(_ queueTask: QueueTask) -> QueueTicket {
        let closure = queueTask.closure
        var queueTask = queueTask
        let ticket = Ticket()
        queueTask.closure = { @Sendable in
            await closure()
            await self.completedTask(ticket)
        }
        return add(queueTask, with: ticket)
    }

    /// Adds a task to the queue.
    /// - Parameters:
    ///   - slots: The number of slots the task requires. Defaults to 1.
    ///   - closure: The work to perform.
    /// - Returns: A `Ticket` that can be passed to `cancel(_:)` to cancel this specific task.
    @discardableResult
    public func add(slots: Int = 1, _ closure: @Sendable @escaping () async -> Void) -> QueueTicket {
        let ticket = Ticket()
        let wrappedClosure = { @Sendable in
            await closure()
            await self.completedTask(ticket)
        }
        return add(.init(slots: slots, closure: wrappedClosure), with: ticket)
    }
    
    /// Adds a task to the queue and waits for it to finish.
    /// - Parameters: slots: The number of slots that the task requires. By default, a task requires 1 slot.
    /// - Parameters: closure: The closure that contains the work that the task should perform.
    /// - Returns: The result of the task.
    /// - Throws: A CancellationError if the task is canceled.
    public func addAndWait<T>(slots: Int = 1, _ closure: @Sendable @escaping () async -> T) async throws -> T {
        // Register a new task and retrieve a ticket for it.
        let ticket = registerTask(slots: slots)
        
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                // Retrieve the task and check if it is still valid (not cancelled)
                guard var task = queueTasks[ticket.ticket], !task.isCancelled else {
                    // If the task could not be retrieved (i.e. cancelled) or is cancelled, immediately resume the continuation with a CancellationError
                    continuation.resume(throwing: CancellationError())
                    return
                }
                // Set the continuation cancel closure to resume the continuation with a CancellationError if the task is cancelled
                task.continuationCancelClosure = {
                    continuation.resume(throwing: CancellationError())
                }
                // Set the closure that will be executed when the task is started
                // This closure also handles resolving the continuation when the task is completed and notifies the TaskQueue that the task is completed.
                task.closure = {
                    let result = await closure()
                    await self.completedTask(ticket.ticket) {
                        continuation.resume(returning: result)
                    }
                }
                // Add the task to the queue
                self.add(task, with: ticket)
            }
        } onCancel: {
            // When the task waiting on the result is cancelled, we cancel the task in the queue.
            Task {
                await self.cancel(ticket)
            }
        }
    }
    
    /// Adds a task to the queue and waits for it to finish.
    /// - Parameters: slots: The number of slots that the task requires. By default, a task requires 1 slot.
    /// - Parameters: closure: The closure that contains the work that the task should perform.
    /// - Returns: The result of the task.
    /// - Throws: A CancellationError if the task is canceled or any type of error thrown by the closure.
    public func addAndWait<T>(slots: Int = 1, _ closure: @Sendable @escaping () async throws -> T) async throws -> T {
        // Register a new task and retrieve a ticket for it.
        let ticket = registerTask(slots: slots)
        
        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                guard var task = queueTasks[ticket.ticket], !task.isCancelled else {
                    // If the task could not be retrieved (i.e. cancelled) or is cancelled, immediately resume the continuation with a CancellationError
                    continuation.resume(throwing: CancellationError())
                    return
                }
                // Set the continuation cancel closure to resume the continuation with a CancellationError if the task is cancelled
                task.continuationCancelClosure = {
                    continuation.resume(throwing: CancellationError())
                }
                // Set the closure that will be executed when the task is started
                // This closure also handles resolving the continuation when the task is completed or exist with an error and notifies the TaskQueue that the task is completed.
                task.closure = {
                    do {
                        let result = try await closure()
                        await self.completedTask(ticket.ticket) {
                            continuation.resume(returning: result)
                        }
                    } catch {
                        await self.completedTask(ticket.ticket) {
                            continuation.resume(throwing: error)
                        }
                    }
                }
                
                // Add the task to the queue
                self.add(task, with: ticket)
            }
        } onCancel: {
            // When the task waiting on the result is cancelled, we cancel the task in the queue.
            Task {
                await self.cancel(ticket)
            }
        }
    }
    
    // MARK: Waiting

    /// Blocks until all tasks that are currently queued or running finish or are cancelled.
    /// 
    /// - Important: Do not call this method from within a task that is running in the queue, as this will cause a deadlock. This method should only be called from outside of the queue, e.g., from another actor or from a nonisolated context.
    /// - Note: Tasks produced by `taskProvider` after this call begins are not included in the wait.
    /// - Throws: A CancellationError on cancellation.
    private func waitFor(_ tickets: [Ticket]) async throws {
        // Wait until a task slot opens (i.e. all tasks ahead are either running or completed)
        try await addAndWait {}
        
        // Register a semaphore using a new ticket.
        let semaphoreTicket = Ticket()
        let semaphore = AsyncSemaphore(value: 0)
        waitForAllSemaphores[semaphoreTicket] = semaphore
        defer { waitForAllSemaphores[semaphoreTicket] = nil }
        
        // Check if there are any remaining tasks that are currently running
        let remainingRunningTasks = Set(tickets).intersection(runningTasks.keys)
        while !remainingRunningTasks.intersection(runningTasks.keys).isEmpty {
            // If there are any remaining running tasks, wait for the semaphore to be signaled. The semaphore will be signaled when a task is completed. After that, we check again if there are any remaining running tasks.
            // This will continue until all tasks are completed.
            try await semaphore.wait()
        }
    }

    /// Blocks until all tasks that are currently queued or running finish or are cancelled.
    /// 
    /// - Important: Do not call this method from within a task that is running in the queue, as this will cause a deadlock. This method should only be called from outside of the queue, e.g., from another actor or from a nonisolated context.
    /// - Throws: A CancellationError on cancellation.
    public func waitForAll() async throws {
        // Store all tasks that we want to wait for
        let waitForTickets = allTickets()
        try await waitFor(waitForTickets)
    }
    
    /// Cancels all tasks that are currently queued but not running. Already running tasks are not canceled.
    /// 
    /// - Note: After queued tasks are removed, the queue is advanced. This may start new work from `taskProvider` if free slots are available.
    public func cancelQueued() {
        let stopAfterNode = queue.tail
        while let ticket = queue.head {
            cancel(.init(ticket), startNext: false)
            if ticket === stopAfterNode {
                break
            }
        }
        startNextTasks()
    }
    
    /// Cancels all explicitly queued tasks and all tasks running at the time of the call.
    /// 
    /// - Note: Since cancelling is cooperative, not all running tasks might be canceled immediately. The function does *not* wait for all tasks to complete their cancellation.
    /// - Note: Provider-generated tasks may start after this call advances the queue and are not automatically cancelled by this invocation.
    public func cancelAll() {
        // Only wait for the currently running tasks as queued tasks are removed immediately and not relevant for the wait.
        let runningTaskTickets = self.runningTasks.keys
        cancelQueued()
        for ticket in runningTaskTickets {
            cancelDequeuedTask(ticket)
        }
        startNextTasks()
    }
    
    /// Cancels all explicitly queued tasks and all tasks running at the time of the call, then waits for those running tasks to complete.
    /// 
    /// - Important: Do not call this method from within a task that is running in the queue, as this will cause a deadlock. This method should only be called from outside of the queue, e.g., from another actor or from a nonisolated context.
    /// - Throws: A CancellationError on cancellation.
    /// - Note: Since cancelling is cooperative, not all running tasks might be canceled immediately.
    /// - Note: Tasks started after this call begins (for example from `taskProvider`) are not included in the wait.
    public func cancelAllAndWait() async throws {
        let waitForTickets = Array(self.runningTasks.keys)
        cancelAll()
        try await waitFor(waitForTickets)
    }
}

// MARK: QueueTask

/// A task that can be added to the queue. The task can be provided with an ID to prevent duplicate tasks from being added to the queue.
public struct QueueTask {

    /// The closure that contains the work that the task should perform.
    /// - Note: Never set this variable on any QueueTask instance that was not guaranteed to be isolated to the actor (e.g., may have been created outside of the actor).
    public fileprivate(set) var closure: @Sendable () async -> Void
    
    /// The priority of the task. If nil, the default priority of the task queue is used.
    public let taskPriority: TaskPriority?
    
    /// The number of slots that the task requires. By default, a task requires 1 slot. If a task requires more than 1 slot, it will only be started if there are enough slots available.
    public let slots: Int
    
    /// A closure that can be called to cancel the continuation that is waiting for the task to finish. Since this closure resumes a continuation, it should only be called once.
    fileprivate var continuationCancelClosure: (@Sendable () -> Void)?
    
    /// A flag that indicates whether the task has been cancelled. This is used to prevent the task from being started if it has already been cancelled.
    fileprivate(set) var isCancelled: Bool = false

    /// A flag that indicates whether the continuation has been resumed. This is used to prevent the continuation from being resumed multiple times.
    fileprivate(set) var continuationResumed: Bool = false

    /// Initializes a new queueable task.
    /// - Parameters: slots: The number of slots that the task requires. By default, a task requires 1 slot.
    /// - Parameters: taskPriority: The priority of the task. If nil, the default priority of the task queue is used.
    /// - Parameters: closure: The closure that contains the work that the task should perform.
    public init(slots: Int = 1, taskPriority: TaskPriority? = nil, closure: @Sendable @escaping () async -> Void) {
        precondition(slots > 0, "QueueTask must require at least 1 slot.")
        self.slots = slots
        self.taskPriority = taskPriority
        self.closure = closure
    }
    
    /// Cancels the task. If the task has already been cancelled, this method does nothing.
    /// If the task has a continuation that has not been marked as resumed, the continuation is resumed with a CancellationError.
    fileprivate mutating func cancel() {
        guard !isCancelled else { return }
        isCancelled = true
        if !continuationResumed, let continuationCancelClosure {
            continuationCancelClosure()
            continuationResumed = true
        }
    }
}

// MARK: - QueueTicket

/// An opaque token representing a task that has been added to a `TaskQueue`.
/// Returned by `TaskQueue.add` - pass it to `TaskQueue.cancel(_:)` to cancel
/// that specific task before or while it runs.
public final class QueueTicket: @unchecked Sendable {
    /// The underlying queue node. Kept internal so `TicketQueue` stays internal.
    internal let node: TicketQueue.Node

    internal init(_ node: TicketQueue.Node) {
        self.node = node
    }

    // The ticket associated with this queued task. Used internally for cancellation and tracking.
    internal var ticket: Ticket {
        node.ticket
    }
}
